/* tslint:disable */
/* eslint-disable */
/**
 * RAG Defender Unified Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Summary of RAGDefender behavior for response.
 */
export interface DefenseSummary {
    'applied': boolean;
    'success': boolean;
    'error': string | null;
    'removed_indices': Array<number>;
    'risk_scores': Array<number>;
    'processing_time_ms': number;
}
/**
 * Score information for a document.
 */
export interface DocumentScoreModel {
    'index': number;
    'risk_score': number;
    'is_removed': boolean;
    'reason'?: string | null;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface IngestCommitRequest {
    'tenant_id'?: string | null;
    'app_id'?: string | null;
    'store_quarantine'?: boolean;
    'retriever_backend'?: string | null;
    'source_adapter'?: string | null;
    'index'?: string | null;
    'documents': Array<IngestDocument>;
    'bucket'?: string | null;
    'data_source_id'?: string | null;
}
export interface IngestCommitResponse {
    'accepted': number;
    'quarantined': number;
    'rejected': number;
    'accepted_doc_ids': Array<string>;
    'quarantined_doc_ids': Array<string>;
    'rejected_doc_ids': Array<string>;
}
export interface IngestDocument {
    /**
     * Optional document identifier
     */
    'doc_id'?: string | null;
    /**
     * Document text/content
     */
    'text': string;
    /**
     * Document metadata, including source_type
     */
    'metadata'?: { [key: string]: any; };
}
export interface IngestSyncRequest {
    [key: string]: any;

    'tenant_id'?: string | null;
    'app_id'?: string | null;
    'store_quarantine'?: boolean;
    'bucket'?: string | null;
    'data_source_id'?: string | null;
    'files'?: Array<string> | null;
}
export interface IngestSyncResponse {
    'source_adapter': string;
    'synced_count': number;
    'accepted': number;
    'quarantined': number;
    'rejected': number;
    'accepted_doc_ids': Array<string>;
    'quarantined_doc_ids': Array<string>;
    'rejected_doc_ids': Array<string>;
}
export interface LocationInner {
}
export interface PolicyEnforcementSummary {
    'policy_mode': string;
    'blocked': boolean;
    'reason': string | null;
    'retriever_backend'?: string | null;
    'legacy_backfill_required'?: boolean;
    'legacy_backfill_completed'?: boolean;
    'risk_acknowledged_at'?: string | null;
}
export interface QuarantineReviewRequest {
    /**
     * Reviewer reason for approve/reject action
     */
    'reason'?: string | null;
    'retriever_backend'?: string | null;
    'incident_id'?: string | null;
    'bucket'?: string | null;
    'data_source_id'?: string | null;
}
export interface QuarantineReviewResponse {
    'doc_id': string;
    'previous_status': string;
    'new_status': string;
    'indexed'?: boolean;
    'index_error'?: string | null;
    'review'?: { [key: string]: any; };
}
/**
 * Request body for RAG query.
 */
export interface RagQueryRequest {
    /**
     * User query
     */
    'query': string;
    /**
     * Number of documents to retrieve (mock retriever)
     */
    'top_k'?: number;
    /**
     * Channel identifier (web, api, mobile, etc.)
     */
    'channel'?: string | null;
    'retriever_backend'?: string | null;
}
/**
 * Response body for RAG query.
 */
export interface RagQueryResponse {
    'request_id': string;
    'tenant_id': string | null;
    'app_id': string;
    'query': string;
    'answer': string;
    'context_docs': Array<string>;
    'defense': DefenseSummary;
    'policy_enforcement': PolicyEnforcementSummary;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
    'input'?: any;
    'ctx'?: object;
}

/**
 * ORCHESTRATORApi - axios parameter creator
 */
export const ORCHESTRATORApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Main RAG endpoint.  Now delegates the core RAG work to the Orchestrator service:   SAMI API -> Orchestrator /v1/rag/execute -> Retriever + RAGDefender + LLM
         * @summary Rag Query
         * @param {RagQueryRequest} ragQueryRequest 
         * @param {string | null} [authorization] 
         * @param {string | null} [xRequestID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ragQuery: async (ragQueryRequest: RagQueryRequest, authorization?: string | null, xRequestID?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ragQueryRequest' is not null or undefined
            assertParamExists('ragQuery', 'ragQueryRequest', ragQueryRequest)
            const localVarPath = `/v1/rag/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            if (xRequestID != null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ragQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ORCHESTRATORApi - functional programming interface
 */
export const ORCHESTRATORApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ORCHESTRATORApiAxiosParamCreator(configuration)
    return {
        /**
         * Main RAG endpoint.  Now delegates the core RAG work to the Orchestrator service:   SAMI API -> Orchestrator /v1/rag/execute -> Retriever + RAGDefender + LLM
         * @summary Rag Query
         * @param {RagQueryRequest} ragQueryRequest 
         * @param {string | null} [authorization] 
         * @param {string | null} [xRequestID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ragQuery(ragQueryRequest: RagQueryRequest, authorization?: string | null, xRequestID?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RagQueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ragQuery(ragQueryRequest, authorization, xRequestID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ORCHESTRATORApi.ragQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ORCHESTRATORApi - factory interface
 */
export const ORCHESTRATORApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ORCHESTRATORApiFp(configuration)
    return {
        /**
         * Main RAG endpoint.  Now delegates the core RAG work to the Orchestrator service:   SAMI API -> Orchestrator /v1/rag/execute -> Retriever + RAGDefender + LLM
         * @summary Rag Query
         * @param {RagQueryRequest} ragQueryRequest 
         * @param {string | null} [authorization] 
         * @param {string | null} [xRequestID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ragQuery(ragQueryRequest: RagQueryRequest, authorization?: string | null, xRequestID?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<RagQueryResponse> {
            return localVarFp.ragQuery(ragQueryRequest, authorization, xRequestID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ORCHESTRATORApi - object-oriented interface
 */
export class ORCHESTRATORApi extends BaseAPI {
    /**
     * Main RAG endpoint.  Now delegates the core RAG work to the Orchestrator service:   SAMI API -> Orchestrator /v1/rag/execute -> Retriever + RAGDefender + LLM
     * @summary Rag Query
     * @param {RagQueryRequest} ragQueryRequest 
     * @param {string | null} [authorization] 
     * @param {string | null} [xRequestID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ragQuery(ragQueryRequest: RagQueryRequest, authorization?: string | null, xRequestID?: string | null, options?: RawAxiosRequestConfig) {
        return ORCHESTRATORApiFp(this.configuration).ragQuery(ragQueryRequest, authorization, xRequestID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SAMIApi - axios parameter creator
 */
export const SAMIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Approve quarantined doc and move it to accepted status; pushes to indexer when enabled.
         * @summary Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveQuarantineDoc: async (docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('approveQuarantineDoc', 'docId', docId)
            // verify required parameter 'quarantineReviewRequest' is not null or undefined
            assertParamExists('approveQuarantineDoc', 'quarantineReviewRequest', quarantineReviewRequest)
            const localVarPath = `/v1/quarantine/{doc_id}/approve`
                .replace('{doc_id}', encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(quarantineReviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Data Ingestion
         * @param {string | null} [authorization] 
         * @param {IngestCommitRequest} [ingestCommitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestCommit: async (authorization?: string | null, ingestCommitRequest?: IngestCommitRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ingest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ingestCommitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ingest Sync
         * @param {string} [source] 
         * @param {string | null} [authorization] 
         * @param {IngestSyncRequest} [ingestSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestSync: async (source?: string, authorization?: string | null, ingestSyncRequest?: IngestSyncRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ingest/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ingestSyncRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reject quarantined doc and mark it as rejected.
         * @summary Reject Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectQuarantineDoc: async (docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('rejectQuarantineDoc', 'docId', docId)
            // verify required parameter 'quarantineReviewRequest' is not null or undefined
            assertParamExists('rejectQuarantineDoc', 'quarantineReviewRequest', quarantineReviewRequest)
            const localVarPath = `/v1/quarantine/{doc_id}/reject`
                .replace('{doc_id}', encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(quarantineReviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SAMIApi - functional programming interface
 */
export const SAMIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SAMIApiAxiosParamCreator(configuration)
    return {
        /**
         * Approve quarantined doc and move it to accepted status; pushes to indexer when enabled.
         * @summary Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuarantineReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveQuarantineDoc(docId, quarantineReviewRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SAMIApi.approveQuarantineDoc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Data Ingestion
         * @param {string | null} [authorization] 
         * @param {IngestCommitRequest} [ingestCommitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingestCommit(authorization?: string | null, ingestCommitRequest?: IngestCommitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngestCommitResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingestCommit(authorization, ingestCommitRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SAMIApi.ingestCommit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ingest Sync
         * @param {string} [source] 
         * @param {string | null} [authorization] 
         * @param {IngestSyncRequest} [ingestSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingestSync(source?: string, authorization?: string | null, ingestSyncRequest?: IngestSyncRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngestSyncResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingestSync(source, authorization, ingestSyncRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SAMIApi.ingestSync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reject quarantined doc and mark it as rejected.
         * @summary Reject Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuarantineReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectQuarantineDoc(docId, quarantineReviewRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SAMIApi.rejectQuarantineDoc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SAMIApi - factory interface
 */
export const SAMIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SAMIApiFp(configuration)
    return {
        /**
         * Approve quarantined doc and move it to accepted status; pushes to indexer when enabled.
         * @summary Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<QuarantineReviewResponse> {
            return localVarFp.approveQuarantineDoc(docId, quarantineReviewRequest, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Data Ingestion
         * @param {string | null} [authorization] 
         * @param {IngestCommitRequest} [ingestCommitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestCommit(authorization?: string | null, ingestCommitRequest?: IngestCommitRequest, options?: RawAxiosRequestConfig): AxiosPromise<IngestCommitResponse> {
            return localVarFp.ingestCommit(authorization, ingestCommitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ingest Sync
         * @param {string} [source] 
         * @param {string | null} [authorization] 
         * @param {IngestSyncRequest} [ingestSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestSync(source?: string, authorization?: string | null, ingestSyncRequest?: IngestSyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<IngestSyncResponse> {
            return localVarFp.ingestSync(source, authorization, ingestSyncRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Reject quarantined doc and mark it as rejected.
         * @summary Reject Quarantine
         * @param {string} docId Document ID
         * @param {QuarantineReviewRequest} quarantineReviewRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<QuarantineReviewResponse> {
            return localVarFp.rejectQuarantineDoc(docId, quarantineReviewRequest, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SAMIApi - object-oriented interface
 */
export class SAMIApi extends BaseAPI {
    /**
     * Approve quarantined doc and move it to accepted status; pushes to indexer when enabled.
     * @summary Quarantine
     * @param {string} docId Document ID
     * @param {QuarantineReviewRequest} quarantineReviewRequest 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public approveQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return SAMIApiFp(this.configuration).approveQuarantineDoc(docId, quarantineReviewRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Data Ingestion
     * @param {string | null} [authorization] 
     * @param {IngestCommitRequest} [ingestCommitRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ingestCommit(authorization?: string | null, ingestCommitRequest?: IngestCommitRequest, options?: RawAxiosRequestConfig) {
        return SAMIApiFp(this.configuration).ingestCommit(authorization, ingestCommitRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ingest Sync
     * @param {string} [source] 
     * @param {string | null} [authorization] 
     * @param {IngestSyncRequest} [ingestSyncRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ingestSync(source?: string, authorization?: string | null, ingestSyncRequest?: IngestSyncRequest, options?: RawAxiosRequestConfig) {
        return SAMIApiFp(this.configuration).ingestSync(source, authorization, ingestSyncRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reject quarantined doc and mark it as rejected.
     * @summary Reject Quarantine
     * @param {string} docId Document ID
     * @param {QuarantineReviewRequest} quarantineReviewRequest 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rejectQuarantineDoc(docId: string, quarantineReviewRequest: QuarantineReviewRequest, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return SAMIApiFp(this.configuration).rejectQuarantineDoc(docId, quarantineReviewRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



